// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using summer_chore_chart.Models;

namespace summer_chore_chart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200610023214_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("summer_chore_chart.Models.BalanceTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Childid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Currenttotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BalanceTrack");
                });

            modelBuilder.Entity("summer_chore_chart.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("summer_chore_chart.Models.Childtrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Childid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Penaltyid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Recorddate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rewardid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Childtrack");
                });

            modelBuilder.Entity("summer_chore_chart.Models.Chorelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Choreamt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chorename")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chorelist");
                });

            modelBuilder.Entity("summer_chore_chart.Models.Penalties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Penaltyamt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Penaltyname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Penalties");
                });
#pragma warning restore 612, 618
        }
    }
}
